from siteclassifier import SiteClassifier
from pprint import pprint

s = SiteClassifier('https://kandmaccountants.co.uk')
s.gohome()
s.findemailaddresses()
s.findcompanyregno()
print("Emails")
print("======")
pprint(s.emails)
print("Sitelinks")
print("=========")
pprint(s.sitelinks)
print("Exludedlinks")
print("############")
pprint(s.excludedlinks)
print("SocialMediaLinks")
print("################")
pprint(s.socialmedialinks)
print("Company Registration Numbers")
print("############################")
print(s.crns)
#pprint(s.roothtml)